apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: '2024-01-16T16:49:22+01:00'
  labels:
    io.kompose.service: newssifter-chatbot
  name: newssifter-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: newssifter-chatbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: '2024-01-16T16:49:22+01:00'
      labels:
        io.kompose.network/newssifter-default: 'true'
        io.kompose.service: newssifter-chatbot
    spec:
      containers:
        - image: newssifter-chatbot:main
          name: newssifter-chatbot
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
