apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-01-16T16:49:22+01:00'
  labels:
    io.kompose.service: newssifter-api
  name: newssifter-api
spec:
  ports:
    - name: '3333'
      port: 3333
      targetPort: 3333
  selector:
    io.kompose.service: newssifter-api
status:
  loadBalancer: {}
