apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-01-16T16:49:22+01:00'
  labels:
    io.kompose.service: newssifter-chatbot
  name: newssifter-chatbot
spec:
  ports:
    - name: '8080'
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: newssifter-chatbot
status:
  loadBalancer: {}
